services:
  controller:
    image: ngrinder/controller
    ports:
      - "8888:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./ngrinder-controller:/opt/ngrinder-controller
  agent:
    image: ngrinder/agent
    links:
      - controller
    depends_on:
      - controller
